Automate-Tinder/Readme.md

Added a Text in the ```README``` of the Automate Tinder.

A Sample PR for PSoC'2020

---

Website_Blocker/README.md
Website_Blocker/web_blocker.py

Added a Python Script for blocking websites.

Rotten scripts 1

---

Hash-The-File/README.md
Hash-The-File/main.py

Hash the file

---

Find-all-Links/README.md
Find-all-Links/main.py

Find all links

---

URL Shortner/README.md
URL Shortner/app.py

Implemented the Url Shortner Automation Script using Python.

Implemented the new Automation Script of url Shortner.

---

Vigenere_Cipher/App.py
Vigenere_Cipher/Readme.md

Added a Vigenere Cipher script to Encrypt and Decrypt text.

Added Vigenere Cipher Script

---

Stock_Market_Data/App.py
Stock_Market_Data/Readme.md

Added python script for getting stock market data on the basis of inputs on CLI.
Closes #60 
For Example : 
```
Please frequency at which to gather the data; common options would include ‘1d’ (daily), ‘1mo’ (monthly), ‘1y’ (yearly): 1d
Please enter the start date in the following format Year-Month-Date: 2020-01-01
Please enter the end date in the following format Year-Month-Date: sde
Error: must be format yyyy-mm-dd 
Please enter the end date in the following format Year-Month-Date: 2020-01-10
Please enter the name of the stock: msft
Date: 2019-12-31 00:00:00--------------------
Opens at : 155.91
Close at : 156.83
Highest : 156.9
Low: 155.59 
Date: 2020-01-02 00:00:00--------------------
Opens at : 157.91
Close at : 159.74
Highest : 159.85
Low: 157.46 
Date: 2020-01-03 …
```

Python script added for Stock Market Data

---

Word-Meaning/App.py
Word-Meaning/Readme.md

Added Python script to get meaning of a english word.
Closes #59

Word_Meaning Added

---

File Organiser/Organiser.py
File Organiser/Readme.md

Made File Organizer Script using Python.

File Organizer - Branch 2

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Create an Issue + Pull Request Template

---

Sports Score Updates/README.md
Sports Score Updates/script.py

Added script to get sports score updates

---

GitHub Graph Populator/README.md
GitHub Graph Populator/github_graph_populator.js
GitHub Graph Populator/package-lock.json
GitHub Graph Populator/package.json

Create GitHub Graph Populator script, a script that can create fake commits to make your GitHub profile look attractive.
Fixes #68

Create GitHub Graph Populator script

---

Generate_Fake_Data/App.py
Generate_Fake_Data/Readme.md

Added Python Script to create Fake Numerical Data for Data Modelling and save it into an `npz` File.
Fixes #69 
```
These are the types of random data you can generate: 
providers
_Generator__config
_Generator__random
address
bothify
building_number
city
city_prefix
city_suffix
country
country_code
geo_coordinate
hexify
latitude
lexify
longitude
military_apo
military_dpo
military_ship
military_state
numerify
postalcode
postalcode_plus4
postcode
random_digit
random_digit_not_null
random_digit_not_null_or_empty
random_digit_or_empty
random_element
random_int
random_letter
random_lowercase_letter
random_number
random_sample
random_sample_unique
random_uppercase_letter
randomize_nb_elements
secondary_address
state
state_abbr
street_address …
```

Added script for generating fake data

---

Countdown_clock_and_Timer/Countdown_timer.py
Countdown_clock_and_Timer/Readme.md

Countdown clock (2)

---

Download Mangas/README.md
Download Mangas/script.py

Added a script to download mangas as PDF (a single chapter or multiple chapters within a range)
Fixes #134

Added script to download mangas as PDF

---

Port Scanner/README.md

updated context

---

Subtitle Downloader/subtitle_downloader/readme.md

Fixes #(12)
Replace `12` with the issue number which is fixed in this PR

Youtube link added

---

Search_File/App.py
Search_File/Readme.md

Added an python script to search a file in a system.
Fixes #174 

Add script to search file in a system

---

Generate_Fake_Data/App.py

Added support for Hindi and English language data in fake data generation script.

Added support for hindi and english language data

---

Desktop_notifier/Readme.md
Desktop_notifier/desktop_notifier.py

A desktop notifier app runs on your system and it will be used to send you notifications after every specific interval of time.

Desktop notifier (3)

---

Substitution_Cypher/App.py
Substitution_Cypher/Readme.md

Added Python script for the Substitution cipher
#154 

Added Python script for Substitution cipher

---

Reddit Wallpaper/README.md
Reddit Wallpaper/script.py

added script to download Reddit images and set it as desktop wallpaper (can be from any subreddit)
Fixes #72

added script to download reddit images and set it as desktop wallpaper

---

Python Library Downloader/README.md
Python Library Downloader/Unix/requirements.txt
Python Library Downloader/Windows/requirements.txt
Python Library Downloader/script.py

Developed the Python Script to download the most frequently used libraries for data science pipeline.
Fixes #132 

Implemented the Python Library Downloader (ML and Data Science).

---

Large File Identifier/README.md
Large File Identifier/scanner.py

Developed the Python Script to identify the large files in a directory/folder.
Fixes #186 

Large file identifier

---

README.md

Add the PClub Summer of Code (PSoC), it's description and logo to README.md
Fixes #131

Add PClub Summer of Code (PSoC) to README.md

---

s3 Bucket Downloader/README.md
s3 Bucket Downloader/s3_bucket_downloader.py

Script to install and configure AWS CLI and use it to download AWS S3 bucket
Fixes #75

Script to download aws s3 bucket

---

Slideshare_slides_downloader/README.md
Slideshare_slides_downloader/requirements.txt
Slideshare_slides_downloader/slideDownloader.py

The script downloads slides from Slideshare and stores them as a pdf using Python.
NOTE: The script works only for slides on 'Slideshare'.
It works in three steps.
-  It goes to the URL of the site and extracts the URLs of individual slides
-  It then downloads all the slides as images and stores them in a temporary folder
- Finally, it appends all the images into a PDF and deletes the temporary folder with the images.
Fixes #204 

Slideshare slides downloader added

---

.github/issues_labeler.yml
.github/workflows/greetings.yml
.github/workflows/issues_labeler.yml

This pr adds Github actions for issue labelling and greetings to the repo.
Fixes #213

Added github actions for issue labelling and greetings

---

Python/Html-to-Markdown/README.md
Python/Html-to-Markdown/html_to_markdown.py

Script to convert all HTML Files to Markdown Format #202

---

Go/README.md

Create a README for Golang Language Directory
Fixes #260 

Created a README for Golang Language Directory

---

Open_Source_Events/CH20/2020.md
Open_Source_Events/CH20/README.md
Open_Source_Events/README.md

Added CH20 to the open-source events folder.
Fixes  issue #265

Added CH20 to the open source events

---

Python/Aws/Readme.md
Python/Aws/createS3Bucket.py
Python/Aws/moveFile.py
Python/Aws/seceretManager.md
Python/Aws/secretManager.py

To add a python script to create a s3 bucket , script to retrieve the decrypted secret value from an AWS Secrets Manager secret and script to move File from s3 bucket to specific destination directory.
Fixes #193   #194  #254  

Solved #193 #194 and #254.

---

Python/RSA_Key_Generation/README.md
Python/RSA_Key_Generation/key_pair_generation.py

Generate Public Keys #276

---

Python/Speech-to-Text/ReadMe.md
Python/Speech-to-Text/requirements.txt
Python/Speech-to-Text/speech-to-text.py

This Script to will Convert Speech to Text in real time
PR -> Script to Convert Speech to Text #250
Fixes #240
- [ ❌] Bug fix (non-breaking change which fixes an issue)
- [ ✔] New feature (non-breaking change which adds functionality)
- [❌ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [✔ ] This change requires a documentation update
- [✔ ] My code follows the style guidelines(Clean Code) of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas
- [✔ ] I have created a helpful and easy to understand README
- [ ❌] I have made corresponding changes to the documentation
- [ ✔] My changes generate no new warnings
- [✔ ] I have added tests/screenshots(If …

Script to Convert Speech to Text

---

Python/Scrape_Twitter/README.md
Python/Scrape_Twitter/Scrape_Twitter.py

Script to scrape tweets from a tag and store them in MongoDB database.
Fixes #301

Scrape twitter

---

Python/Base64_Encoder_Decoder/ConvertToBase64.py
Python/Base64_Encoder_Decoder/README.md

Python Script to Encode and Decode BASE 64 String to utf-8 string and vice versa.
Fixes #346 
- [Y] Bug fix (non-breaking change which fixes an issue)
- [Y] New feature (non-breaking change which adds functionality)
- [Y ] My code follows the style guidelines(Clean Code) of this project
- [ Y] I have commented my code, particularly in hard-to-understand areas
- [Y ] I have created a helpful and easy to understand `README.md`

Base64 encoder and decoder in Python 

---

README.md

There were some grammatical errors in the README.md file. Fixed them up and changed some of the sentences which might seem more appealing to the viewer or the contributor. 

Fixed some grammatical errors

---

Python/Email_Scrape_From_Webpage/README.md
Python/Email_Scrape_From_Webpage/webpage-email-scrape.py

A Script to scrape all the Emails present on the webpage using Python.

Script to scrap all the E-Mails from a webpage.

---

JavaScript/Base64_Encoder_Decoder/Decoder_Encoder(Browser).js
JavaScript/Base64_Encoder_Decoder/Decoder_Encoder(Node).js
JavaScript/Base64_Encoder_Decoder/README.md
JavaScript/README.md

JS Script to Encode and Decode BASE 64 String to utf-8 string and vice versa.Fixes #(issue_no)
Fixes #346

Base64 encoder and decoder is added

---

.github/workflows/stale.yml

Added a Github Action to mark issues as Stale #367

---

Python/Aws/s3ToRedshift.md
Python/Aws/s3ToRedshift.py

Loading data from Amazon S3 to Redshift
Fixes #392

solved #392 added : Loading data from Amazon S3 to Redshift

---

Python/CRICBUZZ scraper/README.md
Python/CRICBUZZ scraper/crik_buzz.py

- This python script will scrap cricbuzz.com to get live scores.
- Pylint Score : **10/10**
Fixes #409 

Python script to get live score

---

Python/Flask_Directory_Initiator/README.md
Python/Flask_Directory_Initiator/flask_init.py
Python/Flask_Directory_Initiator/requirements.txt

Added a python script to initiate flask directory and setup a virtual environment within that directory. Includes the script file and a readme with steps to run the script.
Modules Used : `virtualenv`, `os`, `sys`.
Fixes #425 

Add Flask_Directory_Initiator

---

Python/Counting_Days/Readme.md
Python/Counting_Days/counting_days.py

This script will calculate the days between today and X.
Fixes #473

Counting Days #432

---

README.md

Added the Stargazers Graph

---

Open_Source_Events/README.md
Open_Source_Events/SLoP/README.md
Open_Source_Events/SLoP/stats.md

I have included SLoP in Open_Source_Events.
I followed the same scheme as used for other Open SOurce events already present in the directory.
Fixes #513 

Added SLoP in Open_Source_Events

---

README.md

Added a Repo Size badge.
Fixes #521

Repo Size badge

---

Python/Track_Data_Usage/track_data_usage.py

Added Meaningful Variable in accordance with #546 
Fixes #546

Added Meaningful Variable

---

.github/workflows/issue_edit.yaml

These changes ensure that all the bugs in the Issue Action have been solved.
Fixes #542

Solved Issue Editing Bug

---

Bash/Ports_Scan/README.md
Bash/Ports_Scan/ports_scan.sh

Added the Bash Script for Finding and Killing process on ports.
Fixes #508

Added Port Scan/Kill using BASH

---

JavaScript/ROT13/README.md
JavaScript/ROT13/rot13.js
Python/ROT13/README.md
Python/ROT13/ROT13.py

this adds a python script which decrypts a rot13 encrypted string.
- [ yes ] My code follows the style guidelines(Clean Code) of this project
- [ yes ] I have performed a self-review of my own code
- [ yes] I have created a helpful and easy to understand `README.md`
- [ yes] I have made corresponding changes to the documentation
- [ yes] My changes generate no new warnings
- [ yes ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

created a rot13 folder

---

.github/auto_assign.yml
.github/workflows/assign_pr.yml

Adds GitHub Actions configuration to auto-assign pull requests
Fixes #631 
Currently added Reviewers
- HarshCasper

Add Auto Assign PR GitHub Action

---

Python/cryptocurrency_converter/README.md
Python/cryptocurrency_converter/crypto_converter.py

Created a script crypto_converter.py
This script can be used as a cryptocurrency to currency converter or vice versa using functions in the code. 
It uses coinbase API.
Fixes #(427)

Cryptocurrency Converter Script

---

Open_Source_Events/SWOC/README.md

I have added information about SWOC (script winter of code)
Fixes #629

info about swoc added

---

Python/Github_Traffic/.env.example
Python/Github_Traffic/README.md
Python/Github_Traffic/github_traffic.py
Python/Github_Traffic/requirement.txt

This script can help in analyzing the traffic on a GitHub repo in the last 2 weeks.
Fixes #569 

GitHub Traffic

---

Bash/Twitter_Bookmarks/README.md
Bash/Twitter_Bookmarks/twitterBookmarks.sh

Added Bash Script for scraping the URL's of the tweets saved as Twitter Bookmark and saving them in a markdown file.
Fixes #(538)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the style guidelines(Clean Code) of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have created a helpful and easy to understand `README.md`
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Twitter Bookmarks

---

Python/README.md

Updated ReadMe File. 
Fixes #627

Updated Python - README.md

---

Bash/Custom_Prompt/README.md
Bash/Custom_Prompt/custom_prompt.sh

Added a bash script for tweaking the command prompt.
Fixes #632 

Add custom prompt script for Bash

---

Bash/URL_Scraper/README.md
Bash/URL_Scraper/url_scraper.sh

This bash script can be used to extract url from a web page directly from the terminal.
Fixes #635 

Add bash URL scraper script

---

Bash/Multiplexing/No_Subtitles_MKV/README.md
Bash/Multiplexing/No_Subtitles_MKV/nosubsmkv.sh

Bash script to remove subtitles from matroska (mkv) files present in a directory.
Fixes #658

No Subtitles Matroska

---

.github/linters/Troubleshoot.md
CONTRIBUTING.md
Python/CONTRIBUTION-GUIDELINE.md
STYLE_GUIDELINES.md

@HarshCasper This is kind of an incomplete PR (will make this draft), but here is the backbone of the styling guideline. I will make a few more changes and upload 2 new files (most probably).
Meanwhile, you can read this and suggest me changes.
Fixes #714 
Update - **Open for Review**

Added Global Styling Guideline

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/script_request.md

Added New Issue templates, Comments and configuration.
Fixes #624 
I have not played with PR template at all.
- I have added a new `script_request` template.
- Made major changes to the `bug_report` and `feature_request` templates.
- Moreover automated the Issue Report flow for more interactivity.
- See if these changes make sense to you

Added New Issue Templates and Configuration

---

Open_Source_Events/MWOC/README.md

A small PR. Added description and image for MWOC in the Open_Source_Events folder keeping the format same as the format of other such READMEs.
Please review and add necessary tags (after adding the necessary workflow) for MWOC before merging this PR. Thanks:)
Fixes #750 

Added MWOC to Open Source Events Directory

---

Python/Subreddit_Image_Scrapper/README.md
Python/Subreddit_Image_Scrapper/script.py

- This script helps you to download images from a particular subreddit in the local system.
- You have a choice:
- To select your favorite Subreddit
- Select the number of images you want to download (go for more than 4)
- Sort method you want. (New, Hot, Top)
Fixes #14

Subreddit image scrapper

---

Python/CONTRIBUTION-GUIDELINE.md
Python/Quantum_random/.env.example
Python/Quantum_random/README.md
Python/Quantum_random/quant_random.py

Fixes #765 
Replace `765` with the issue number which is fixed in this PR

Quantum computing script updates

---

Python/Stopmotion/README.md
Python/Stopmotion/main.py

Fixes #799
Replace `799` with the issue number which is fixed in this PR

Stop motion script

---

README.md

docs: updated README.md for Bash and powershell

---

README.md

As this project is maintained by many folks soo projects admin is replaced by project maintainers.
Fixes #805 

added maintiners in place of project admin

---

Open_Source_Events/GSSOC/README.md
Open_Source_Events/README.md

Added GSSOC in Open_Source_Events directory.
Fixes #831

Added GSSOC in Open_Source_Events

---

Python/Twitter_Hashtags/Hashtag_Scrape.py
Python/Twitter_Hashtags/README.md

This script makes use of snscrape to scrape tweets associated with a particular hashtag. Snscrape is a python library that scrapes twitter without the use of API keys. Here, we take the input of a hashtag and generate details associated with it (Eg., id, username, date, time, the tweet content, number of replies, likes, retweets, quotes and also its URL) tracing upto the desired number of tweets. We store all this information in a .csv file with the selected file name.
Fixes #579 

Adding files for #579

---

Python/Coderforces_Problem_Scrapper/Codeforces_problem_scrapper.py
Python/Coderforces_Problem_Scrapper/README.md
Python/Coderforces_Problem_Scrapper/requirements.txt

This python script will let you download Problem Statements from Codeforces and save them as a pdf file. The script uses Selenium Webdriver, Pillow and fpdf library. Selenium is used with Chrome Webdriver, so having Chrome browser is a requirement.
Fixes #291

Added Coderforces Scraping files to Codeforces_Scraper

---

.github/linters/.python-lint.yml

Ignored alert from pylint about module docstring
Fixes #849

chore(pylint) : Ignore module doc string from pylint

---

Bash/KhanAcademy_Downloader/README.md
Bash/KhanAcademy_Downloader/khanacademy-dl.sh

Added a bash script to download videos from Khan Academy using youtube-dl.
Closes #807

Add Khan Academy Downloader bash script

---

Python/Cryptocurrency_Converter/crypto_converter.py

Fixes #427 
As suggested by @vybhav72954 and @sohamsshah  , I've added a few functionalities into the old CLI version of the `Cryptocurrency_Converter` directory within the `Python` directory and hence updated it.  
**Updated script now** :  
*  has a better user interaction.
* has went through a fix-up of a few major function call errors.
* has went through a fix-up of a few minor syntax and documentation error.
* has an ability to handle bad input by the user.
I'll attach the snapshot of a few output cases below.

Update and Add functionalities to the old CLI ver. of Cryptocurrency Converter (Fixed and Refactored.)

---

Python/Scrap_Latest_Torrents/README.md
Python/Scrap_Latest_Torrents/requirements.txt
Python/Scrap_Latest_Torrents/scrap_latest_torrents.py

This script downloads the torrents in our Torrent client from the website https://rarbg.to/ from an entered label.
Fixes #165

Add Scrap Latest Torrents

---

Python/Automate_Telegram/README.md

Am I doing any mistakes in placing PR. As I found the link to be broken I have change it. Hope You find it useful.

Changed the link -> issue #870

---

Python/Get_Lyrics/get_lyrics.py

**Before**
`'NoneType' object has no attribute 'findAll'`
**Test case**
***`python get_lyrics.py --artist "Taylor Swift" --song "love Story"`***
*Example*:
`Artist Name: Taylor Swift`
`Song Name: Love Story`
```
artist="".join(artist.lower().split())
song="".join(song.lower().split())
```
- *Function* def get_lyrics(artist, song):
- To update the artist and song name to lowercase removing spaces  so that the response url formed is correct.

Updated get_lyrics.py to accept strings with spaces and Uppercase 

---

Python/Wikipedia_Footballer_Scraper/README.md
Python/Wikipedia_Footballer_Scraper/main.py
Python/Wikipedia_Footballer_Scraper/requirements.txt

This script helps to scrape Wikipedia to obtain a Football player's club career data using BeautifulSoup library. The user gives the input of the name of any popular Football player and generate the club career details associated with them.
Fixes #466 

Footballer club info wikipedia scraper for issue #466

---

Open_Source_Events/CrossWOC/README.md

Added CrossWOC in Open Source Events!
Fixes #751

Added CWOC in Open Source Events

---

Python/Linkedin_Connection_Scrapper/Readme.md
Python/Linkedin_Connection_Scrapper/credentials.json
Python/Linkedin_Connection_Scrapper/main.py

Added Linkedin_Connection_Scrapper  Script Using Python
Fixes #375
Scraps the Following data from Each Connection
- Name
- Linkedin_URL
- Latest_JOB_Position
- Skills

Added Linkedin_Scrapper Script

---

Python/Create_Word_Cloud/README.md

Updating readme

---

Python/Create_Word_Cloud/create_word_cloud.py

By introducing this feature we can generate word cloud by input of csv files also.
Fixes #841 

Adding extra feature

---

Python/Aws_EC2/.env.example
Python/Aws_EC2/README.md
Python/Aws_EC2/create_ec2_instance.py

Fix #847 
This python script will generate a keypair for your aws ec2 instance and also store it in your local machine.
After keypair is generated, it will create an instance provided with the ami-ID.

New aws ec2 python script

---

Python/BitCoin Mining/BitCoin_Mining.py
Python/BitCoin Mining/README.md
Python/BitCoin Mining/ReadMe.md.txt

Added Bitcoin mining Script

---

Python/PR_Workflow/README.md
Python/PR_Workflow/prw.py
Python/PR_Workflow/src/drivefunc.py
Python/PR_Workflow/src/extracktor.py
Python/PR_Workflow/src/graphqlapi.py

Update PR_workflow script. As you might have noticed, there is option for verbose mode but the feature is missing
i want to work on this and want to add verbose mode in it.
Fixes #923 
@HarshCasper 

 Verbose mode added and Improve output formatting #923

---

Python/Background_Subtractor/BG_Subtractor.py
Python/Background_Subtractor/README.md
Python/Background_Subtractor/requirements.txt

This python script lets you remove background form image by keeping only foreground in focus. By using Grabcut Algorithm it makes easy to do the task.
Fixes #821

#821 Background subtractor files added

---

Python/Email_Scrape_From_Commits/README.md
Python/Email_Scrape_From_Commits/email_scrape.py
Python/Email_Scrape_From_Commits/install.sh
Python/Email_Scrape_From_Commits/requirements.txt

Script to Scrape email and other details from commits
Fixes #927 

Reverse Engineer Commits to fetch E-Mail Address #927

---

Go/Port_Scanner/port_scanner.go

Fixed some of the incorrect syntax and formatted the code a bit.
Fixes #957

Resolved syntax errors

---

.gitignore
JavaScript/Twitter_Followers_Overlap/README.md
JavaScript/Twitter_Followers_Overlap/apiTokens.js
JavaScript/Twitter_Followers_Overlap/package-lock.json
JavaScript/Twitter_Followers_Overlap/package.json
JavaScript/Twitter_Followers_Overlap/twitterFunc.js
JavaScript/Twitter_Followers_Overlap/twitter_followers_overlap.js

Twitter_Followers_Overlap a script to list the followers that are common between two Twitter users.
Fixes #1004

Script addition : Twitter followers overlap

---

Python/Pomodoro_Timer/Pomodoro.py
Python/Pomodoro_Timer/README.md
Python/Pomodoro_Timer/block_urls.txt

The python script covers the implementation of Pomodoro Timer consisting of 25 minutes of working intervals broken by 5 minutes of break time. It also has a feature to block websites to increase focus.
Fixes #942 

Command line based Pomodoro Timer

---

Python/Email_Scrape_From_Webpage/webpage-email-scrape.py

FeatureNotFound bug corrected

---

.github/actions/PR_has_a_valid_issue/Dockerfile
.github/actions/PR_has_a_valid_issue/action.yml
.github/actions/PR_has_a_valid_issue/main.py
.github/workflows/Check if issue exists.yml

There was a need to automate PR body validation, check for valid issue numbers, and apply a corresponding decission if true or false. (This is the first action out of two)
The GitHub action can be viewed in action from [here](https://github.com/XZANATOL/Github-actions-test/pull/18)
Fixes #757

Added GitHub actions to validate issue number in PR bodies

---

JavaScript/Hashnode_Scripts/Readme.md
JavaScript/Hashnode_Scripts/package-lock.json
JavaScript/Hashnode_Scripts/package.json
JavaScript/Hashnode_Scripts/script.js

Fixes #738 
This Script will Will Store Best required Posts from Hashnode With their title , Brief Summary and author name in a CSV FIle.
Sample Output is Shown in README.
Some wrong changes in PR #972 
Result in this PR

Script Added

---

Python/Bulk_File_Renamer/README.md
Python/Bulk_File_Renamer/main.py
Python/Bulk_File_Renamer/utils.py

Created python script for handling bulk file renaming and relocation.
Fixes #1000 

Bulk File Renamer

---

Python/Pwned_Passwords/.env.example
Python/Pwned_Passwords/README.md
Python/Pwned_Passwords/pwned_checker.py
Python/Pwned_Passwords/requirements.txt

The python script checks if a password has been exposed to a data breach and the number of time it has occured, thus proving the password to be vulnerable for further attacks.
Fixes #993 

Password Vulnerability Test

---

.github/workflows/greeting.yml

Fixes #924 
Added greeting.yml .
Github Bot will Comment on Opening of  Issues and PRs 
Also for merging of PRs

added action for greeting to all

---

Python/Wikipedia Scraper/InfoboxScraper.py
Python/Wikipedia Scraper/README.md

The infobox provides all the necessary factoids and overall summary of any topic. This python script will be capable of scraping the infobox of wikipedia pages and present it.
Fixes #1081

Wikipedia infobox scraper

---

Python/Linkedin_Video_Downloader/README.md

Demo gif in Linkedin Video Downloader is Corrected
Fixes #1084

corrected demo gif

---

JavaScript/Markdown_To_HTML/README.md
JavaScript/Markdown_To_HTML/markdown.md
JavaScript/Markdown_To_HTML/package.json
JavaScript/Markdown_To_HTML/script.js
JavaScript/README.md

Added a script that converts a markdown file to it's corresponding html file
Fixes #869 

Markdown to HTML

---

README.md

This fixes #1114 
**1. aligned the badges to the center**
**2. made them of single type**

aligned the badges to center

---

MAINTAINERS.md

Made changes to maintainers.md and created Pull Request to update the same.

Added Rohini Rao in maintainers.md

---

MAINTAINERS.md

Added Akhil Bhalerao in Maintainers.md

---

Python/Internshala_Scrapper/internshala-scraper.py

range -> Enumeration
input -> print

Functionality improvements

---

OPEN_SOURCE_EVENTS.md

Fixes #1110 
I have added LetsGrowMore summer of code in OPEN_SOURCE_EVENTS.md. I have also added the time period and website link for the same.
Please review my PR.

Added LetsGrowMore summer of code in OPEN_SOURCE_EVENTS.md

---

CONTRIBUTING.md

I have assigned the section covering the basics of Git and GitHub at the start so that newbie contributors can took a look at that rather than just blindly following the commands described in the next section.

Modified the arrangement of sections

---

Python/Linkedin_Learning_Video_Downloader/.sample.env
Python/Linkedin_Learning_Video_Downloader/README.md
Python/Linkedin_Learning_Video_Downloader/requirements.txt
Python/Linkedin_Learning_Video_Downloader/script.py

added linkedin-learning-videos-downloader

---

STYLE_GUIDELINES.md

Fix Grammatical mistakes and typos found in STYLE_GUIDELINES.md

---

Python/Video to PDF(CLI)/README.md
Python/Video to PDF(CLI)/my_pdf.pdf
Python/Video to PDF(CLI)/requirements.txt
Python/Video to PDF(CLI)/video_to_pdf.py

A script to convert a video into a pdf file. It uses the MoviePy, FPDF and speech recognition modules.
Fixes #1155 

Video to pdf (CLI)

---

Python/Shutdown_Your_System/shutdown_your_system.py

Renamed commando to command which was mistyped.
Fixed typo.

Fixed typo

---

Python/Fb_Request_Accepter/.sample.env
Python/Fb_Request_Accepter/README.md
Python/Fb_Request_Accepter/requirements.txt
Python/Fb_Request_Accepter/script.py
Python/README.md

added facebook request accepter

---

Python/Twitter_Giveaway/.sample.env
Python/Twitter_Giveaway/Readme.md
Python/Twitter_Giveaway/requirements.txt
Python/Twitter_Giveaway/script.py

twitter-giveway script

---

.gitignore
Python/GD_Content_Downloader/.gitignore
Python/GD_Content_Downloader/Readme.md
Python/GD_Content_Downloader/requirements.txt
Python/GD_Content_Downloader/script.py

Fixes #318 
- x ] New feature (non-breaking change which adds functionality)

added Gd_content_downloader

---

Python/Flask_Directory_Initiator/flask_init.py
Python/GD_Content_Downloader/script.py
Python/Human_Detector/human_detector.py
Python/JSON_to_YAML/json_to_yaml.py
Python/Job_Scraper/JobScraper.py
Python/Linkedin_Connection_Scrapper/main.py
Python/Linkedin_Disconnect/script.py
Python/Substitution_Cypher/substitution_cypher.py
Python/Tags_Scraper/Fetch_Tags.py
Python/Telegram_Bot/riddles.py
Python/Video_Steganography/main.py
Python/Video_Watermarker/app.py
Python/Video_to_Frames/video_to_frames.py
Python/Watermark_It/watermark_it.py
Python/Whatsapp_SMS_Bomber/whatsapp_sms_bomber.py

Co-authored-by: deepsource-autofix[bot] <62050782+deepsource-autofix[bot]@users.noreply.github.com>
Comparisons to the singleton objects, like `True`, `False`, and `None`, should be done with identity, not equality. Use `is` or `is not`.
Identity checks are faster than equality checks.

Use identity check for comparison to a singleton (#1)

---

Python/Fetch_Contributions/fetch_contributions.py

Fixed the organization link as previously the code was using a old layout page link
Fixes #1234

:hammer: fixed fetch contribution script

---

Python/Tags_Scraper/Fetch_Tags.py

No certificate validation detected for HTTP request.Disabling certificate validation for HTTP request leave application vulnerable to man-in-the-middle attacks.
Fixing security issue
Fixes #1279 

Fixing security issue 1279

---

Python/Movie-Info-Telegram-Bot/bot.py

Updated functions so they do not contain unused arguments

Removed unused arguments in functions

---

Python/Automate_Image_Caption/caption_generator_Xception.py
Python/Substitution_Cypher/substitution_cypher.py
Python/Telegram_Bot/markovmeme/_main.py
Python/Telegram_Bot/markovmeme/gil.py
Python/Telegram_Bot/markovmeme/main.py

Multiple imports for an import name fixed.
Fixes #(PYL-W0404)
Replace `PYL-W0404` with the issue number which is fixed in this PR

Multiple imports for an import name fixed (PYL-W0404)

---

JavaScript/Edit_Webpage/editWebpage.js

Fix typo in editWebpage.js which changes aiitrubte to attribute.

Fix typo aiitribute -> attribute

---

Python/Send_Emails/send_emails.py

add getpass module for password input

Update by JaxBCD

---

JavaScript/Twitter_Unfollowers/Twitter_Unfollowers.js

(Bug fix): Twitter Unfollowers API Node script wasn't working as expected.
